// Mock data for development to avoid CORS issues
export const mockDaycares = [
  {
    operation_number: "1234567",
    operation_name: "Happy Kids Daycare",
    operation_type: "Licensed Center",
    address: "123 Main St",
    city: "Austin",
    county: "Travis",
    phone: "512-555-1234",
    capacity: "85",
    email: "info@happykids.example.com",
    website: "https://happykids.example.com",
    hours: "Monday-Friday: 7:00am-6:00pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "6 weeks - 5 years",
    rating: {
      score: 4.5,
      stars: "★★★★★",
      class: "excellent",
      yearsInOperation: 7
    },
    price: 1450,
    estimated_price: 1450,
    inspection_date: "2024-01-15",
    total_violations_2yr: 3,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 2,
    low_risk_violations: 0,
    total_inspections_2yr: 8,
    license_issue_date: "2017-03-22",
    temporarily_closed: "NO"
  },
  {
    operation_number: "2345678",
    operation_name: "Sunshine Learning Center",
    operation_type: "Licensed Center",
    address: "456 Oak Ave",
    city: "Austin",
    county: "Travis",
    phone: "512-555-2345",
    capacity: "120",
    email: "contact@sunshinelearning.example.com",
    website: "https://sunshinelearning.example.com",
    hours: "Monday-Friday: 6:30am-6:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, After School",
    ages: "6 weeks - 12 years",
    rating: {
      score: 4.8,
      stars: "★★★★★",
      class: "excellent",
      yearsInOperation: 9
    },
    price: 1550,
    estimated_price: 1550,
    inspection_date: "2024-02-10",
    total_violations_2yr: 1,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 0,
    low_risk_violations: 1,
    total_inspections_2yr: 7,
    license_issue_date: "2015-05-12",
    temporarily_closed: "NO"
  },
  {
    operation_number: "3456789",
    operation_name: "Little Explorers Academy",
    operation_type: "Licensed Center",
    address: "789 Pine Blvd",
    city: "Dallas",
    county: "Dallas",
    phone: "214-555-3456",
    capacity: "75",
    email: "hello@littleexplorers.example.com",
    website: "https://littleexplorers.example.com",
    hours: "Monday-Friday: 7:30am-5:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Toddler, Pre-K, Kindergarten",
    ages: "18 months - 6 years",
    rating: {
      score: 4.2,
      stars: "★★★★",
      class: "good",
      yearsInOperation: 5
    },
    price: 1350,
    estimated_price: 1350,
    inspection_date: "2024-01-28",
    total_violations_2yr: 5,
    high_risk_violations: 0,
    medium_high_risk_violations: 2,
    medium_risk_violations: 1,
    low_risk_violations: 2,
    total_inspections_2yr: 6,
    license_issue_date: "2019-09-30",
    temporarily_closed: "NO"
  },
  {
    operation_number: "4567890",
    operation_name: "Tiny Tots Child Care",
    operation_type: "Licensed Center",
    address: "101 Elm St",
    city: "Houston",
    county: "Harris",
    phone: "713-555-4567",
    capacity: "60",
    email: "info@tinytots.example.com",
    website: "https://tinytots.example.com",
    hours: "Monday-Friday: 7:00am-6:00pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "3 months - 5 years",
    rating: 4.0,
    inspection_date: "2023-12-05",
    total_violations_2yr: 8,
    high_risk_violations: 1,
    medium_high_risk_violations: 2,
    medium_risk_violations: 3,
    low_risk_violations: 2,
    total_inspections_2yr: 8,
    license_issue_date: "2016-11-15",
    temporarily_closed: "NO"
  },
  {
    operation_number: "5678901",
    operation_name: "Bright Beginnings Preschool",
    operation_type: "Licensed Center",
    address: "202 Cedar Lane",
    city: "San Antonio",
    county: "Bexar",
    phone: "210-555-5678",
    capacity: "90",
    email: "contact@brightbeginnings.example.com",
    website: "https://brightbeginnings.example.com",
    hours: "Monday-Friday: 6:45am-6:15pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, Spanish Immersion",
    ages: "6 weeks - 5 years",
    rating: 4.7,
    inspection_date: "2024-02-20",
    total_violations_2yr: 2,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 7,
    license_issue_date: "2018-04-10",
    temporarily_closed: "NO"
  },
  {
    operation_number: "6789012",
    operation_name: "Kids First Daycare",
    operation_type: "Licensed Center",
    address: "303 Maple Dr",
    city: "Fort Worth",
    county: "Tarrant",
    phone: "817-555-6789",
    capacity: "65",
    email: "hello@kidsfirst.example.com",
    website: "https://kidsfirst.example.com",
    hours: "Monday-Friday: 7:15am-5:45pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Toddler, Pre-K",
    ages: "12 months - 5 years",
    rating: 3.9,
    inspection_date: "2023-11-15",
    total_violations_2yr: 7,
    high_risk_violations: 0,
    medium_high_risk_violations: 3,
    medium_risk_violations: 2,
    low_risk_violations: 2,
    total_inspections_2yr: 6,
    license_issue_date: "2020-02-28",
    temporarily_closed: "NO"
  },
  {
    operation_number: "7890123",
    operation_name: "Little Learners Academy",
    operation_type: "Licensed Center",
    address: "404 Birch Ct",
    city: "Austin",
    county: "Travis",
    phone: "512-555-7890",
    capacity: "110",
    email: "info@littlelearners.example.com",
    website: "https://littlelearners.example.com",
    hours: "Monday-Friday: 7:00am-6:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, After School",
    ages: "6 weeks - 10 years",
    rating: 4.3,
    inspection_date: "2024-01-05",
    total_violations_2yr: 4,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 2,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2016-08-15",
    temporarily_closed: "NO"
  },
  {
    operation_number: "8901234",
    operation_name: "Rainbow Kids Childcare",
    operation_type: "Licensed Center",
    address: "505 Willow Way",
    city: "Dallas",
    county: "Dallas",
    phone: "214-555-8901",
    capacity: "80",
    email: "contact@rainbowkids.example.com",
    website: "https://rainbowkids.example.com",
    hours: "Monday-Friday: 6:30am-6:00pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "6 weeks - 5 years",
    rating: 4.1,
    inspection_date: "2023-12-12",
    total_violations_2yr: 6,
    high_risk_violations: 0,
    medium_high_risk_violations: 2,
    medium_risk_violations: 3,
    low_risk_violations: 1,
    total_inspections_2yr: 7,
    license_issue_date: "2017-10-25",
    temporarily_closed: "NO"
  },
  {
    operation_number: "9012345",
    operation_name: "Growing Minds Daycare",
    operation_type: "Licensed Center",
    address: "606 Spruce St",
    city: "Houston",
    county: "Harris",
    phone: "713-555-9012",
    capacity: "95",
    email: "hello@growingminds.example.com",
    website: "https://growingminds.example.com",
    hours: "Monday-Friday: 7:00am-6:15pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Infant, Toddler, Pre-K, Montessori",
    ages: "3 months - 6 years",
    rating: 4.6,
    inspection_date: "2024-02-05",
    total_violations_2yr: 2,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2018-05-20",
    temporarily_closed: "NO"
  },
  {
    operation_number: "0123456",
    operation_name: "ABC Learning Center",
    operation_type: "Licensed Center",
    address: "707 Aspen Ave",
    city: "San Antonio",
    county: "Bexar",
    phone: "210-555-0123",
    capacity: "70",
    email: "info@abclearning.example.com",
    website: "https://abclearning.example.com",
    hours: "Monday-Friday: 7:30am-5:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Toddler, Pre-K",
    ages: "18 months - 5 years",
    rating: 4.0,
    inspection_date: "2023-11-10",
    total_violations_2yr: 5,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 2,
    low_risk_violations: 2,
    total_inspections_2yr: 6,
    license_issue_date: "2019-07-15",
    temporarily_closed: "NO"
  },
  {
    operation_number: "1357924",
    operation_name: "Kiddie Academy",
    operation_type: "Licensed Center",
    address: "808 Redwood Rd",
    city: "Austin",
    county: "Travis",
    phone: "512-555-1357",
    capacity: "120",
    email: "contact@kiddieacademy.example.com",
    website: "https://kiddieacademy.example.com",
    hours: "Monday-Friday: 6:45am-6:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, After School, Summer Programs",
    ages: "6 weeks - 12 years",
    rating: 4.9,
    inspection_date: "2024-01-18",
    total_violations_2yr: 1,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 0,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2015-03-10",
    temporarily_closed: "NO"
  },
  {
    operation_number: "2468135",
    operation_name: "Tiny Treasures Childcare",
    operation_type: "Licensed Center",
    address: "909 Fir Lane",
    city: "Dallas",
    county: "Dallas",
    phone: "214-555-2468",
    capacity: "55",
    email: "hello@tinytreasures.example.com",
    website: "https://tinytreasures.example.com",
    hours: "Monday-Friday: 7:15am-5:45pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Infant, Toddler",
    ages: "6 weeks - 3 years",
    rating: 4.2,
    inspection_date: "2023-12-20",
    total_violations_2yr: 4,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 1,
    low_risk_violations: 2,
    total_inspections_2yr: 7,
    license_issue_date: "2019-11-05",
    temporarily_closed: "NO"
  },
  {
    operation_number: "3691248",
    operation_name: "Stepping Stones Preschool",
    operation_type: "Licensed Center",
    address: "1010 Sycamore Dr",
    city: "Houston",
    county: "Harris",
    phone: "713-555-3691",
    capacity: "85",
    email: "info@steppingstones.example.com",
    website: "https://steppingstones.example.com",
    hours: "Monday-Friday: 7:00am-6:00pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Toddler, Pre-K, Kindergarten",
    ages: "18 months - 6 years",
    rating: 4.4,
    inspection_date: "2024-02-15",
    total_violations_2yr: 3,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2017-06-20",
    temporarily_closed: "NO"
  },
  {
    operation_number: "4567891",
    operation_name: "Future Leaders Academy",
    operation_type: "Licensed Center",
    address: "1111 Magnolia Blvd",
    city: "San Antonio",
    county: "Bexar",
    phone: "210-555-4567",
    capacity: "100",
    email: "contact@futureleaders.example.com",
    website: "https://futureleaders.example.com",
    hours: "Monday-Friday: 6:30am-6:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, After School",
    ages: "6 weeks - 10 years",
    rating: 4.7,
    inspection_date: "2024-01-25",
    total_violations_2yr: 2,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2016-09-15",
    temporarily_closed: "NO"
  },
  {
    operation_number: "5678912",
    operation_name: "Playful Paths Daycare",
    operation_type: "Licensed Center",
    address: "1212 Cherry St",
    city: "Fort Worth",
    county: "Tarrant",
    phone: "817-555-5678",
    capacity: "65",
    email: "hello@playfulpaths.example.com",
    website: "https://playfulpaths.example.com",
    hours: "Monday-Friday: 7:30am-5:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "6 weeks - 5 years",
    rating: 3.8,
    inspection_date: "2023-11-20",
    total_violations_2yr: 9,
    high_risk_violations: 1,
    medium_high_risk_violations: 3,
    medium_risk_violations: 3,
    low_risk_violations: 2,
    total_inspections_2yr: 6,
    license_issue_date: "2020-04-10",
    temporarily_closed: "NO"
  },
  {
    operation_number: "6789123",
    operation_name: "Nurturing Nook Child Care",
    operation_type: "Licensed Center",
    address: "1313 Holly Lane",
    city: "Austin",
    county: "Travis",
    phone: "512-555-6789",
    capacity: "75",
    email: "info@nurturingnook.example.com",
    website: "https://nurturingnook.example.com",
    hours: "Monday-Friday: 7:00am-6:15pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "6 weeks - 5 years",
    rating: 4.5,
    inspection_date: "2024-02-10",
    total_violations_2yr: 2,
    high_risk_violations: 0,
    medium_high_risk_violations: 0,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 7,
    license_issue_date: "2018-02-12",
    temporarily_closed: "NO"
  },
  {
    operation_number: "7891234",
    operation_name: "Creative Kids Learning Center",
    operation_type: "Licensed Center",
    address: "1414 Ivy Rd",
    city: "Dallas",
    county: "Dallas",
    phone: "214-555-7891",
    capacity: "90",
    email: "contact@creativekids.example.com",
    website: "https://creativekids.example.com",
    hours: "Monday-Friday: 6:45am-6:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K, After School, Arts Programs",
    ages: "6 weeks - 10 years",
    rating: 4.6,
    inspection_date: "2024-01-05",
    total_violations_2yr: 3,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 1,
    low_risk_violations: 1,
    total_inspections_2yr: 8,
    license_issue_date: "2017-07-25",
    temporarily_closed: "NO"
  },
  {
    operation_number: "8912345",
    operation_name: "Blossoming Buds Preschool",
    operation_type: "Licensed Center",
    address: "1515 Walnut Ave",
    city: "Houston",
    county: "Harris",
    phone: "713-555-8912",
    capacity: "80",
    email: "hello@blossomingbuds.example.com",
    website: "https://blossomingbuds.example.com",
    hours: "Monday-Friday: 7:15am-5:45pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Toddler, Pre-K, Kindergarten",
    ages: "18 months - 6 years",
    rating: 4.3,
    inspection_date: "2023-12-12",
    total_violations_2yr: 4,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 2,
    low_risk_violations: 1,
    total_inspections_2yr: 7,
    license_issue_date: "2018-10-05",
    temporarily_closed: "NO"
  },
  {
    operation_number: "9123456",
    operation_name: "Wonder Years Child Care",
    operation_type: "Licensed Center",
    address: "1616 Juniper St",
    city: "San Antonio",
    county: "Bexar",
    phone: "210-555-9123",
    capacity: "85",
    email: "info@wonderyears.example.com",
    website: "https://wonderyears.example.com",
    hours: "Monday-Friday: 7:00am-6:00pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "Yes",
    programs_provided: "Infant, Toddler, Pre-K",
    ages: "6 weeks - 5 years",
    rating: 4.2,
    inspection_date: "2024-01-30",
    total_violations_2yr: 5,
    high_risk_violations: 0,
    medium_high_risk_violations: 1,
    medium_risk_violations: 2,
    low_risk_violations: 2,
    total_inspections_2yr: 7,
    license_issue_date: "2017-12-10",
    temporarily_closed: "NO"
  },
  {
    operation_number: "1234890",
    operation_name: "Little Scholars Daycare",
    operation_type: "Licensed Center",
    address: "1717 Poplar Dr",
    city: "Austin",
    county: "Travis",
    phone: "512-555-1234",
    capacity: "70",
    email: "contact@littlescholars.example.com",
    website: "https://littlescholars.example.com",
    hours: "Monday-Friday: 7:30am-5:30pm",
    days: "Monday-Friday",
    accepts_cccsubsidy: "No",
    programs_provided: "Toddler, Pre-K",
    ages: "18 months - 5 years",
    rating: 4.0,
    inspection_date: "2023-11-15",
    total_violations_2yr: 7,
    high_risk_violations: 0,
    medium_high_risk_violations: 2,
    medium_risk_violations: 3,
    low_risk_violations: 2,
    total_inspections_2yr: 6,
    license_issue_date: "2019-08-20",
    temporarily_closed: "NO"
  }
];

export const mockViolations = [
  {
    violation_id: "V123456",
    operation_number: "1234567",
    operation_name: "Happy Kids Daycare",
    standard_number: "746.3601(a)(1)",
    standard_description: "All children must be signed in and out of the center by a parent or guardian.",
    violation_description: "During inspection, it was observed that 3 children were not properly signed in for the day.",
    corrective_action: "Facility must ensure all children are properly signed in and out by a parent or guardian each day.",
    risk_level: "Medium",
    corrected_at_inspection: "Yes",
    violation_date: "2023-12-15",
    corrected_date: "2023-12-15"
  },
  {
    violation_id: "V123457",
    operation_number: "1234567",
    operation_name: "Happy Kids Daycare",
    standard_number: "746.3407(a)",
    standard_description: "Children must have access to drinking water at all times.",
    violation_description: "During inspection, it was observed that drinking water was not readily accessible to children in the outdoor play area.",
    corrective_action: "Facility must ensure drinking water is accessible to children at all times, including during outdoor play.",
    risk_level: "Medium",
    corrected_at_inspection: "No",
    violation_date: "2023-12-15",
    corrected_date: "2023-12-22"
  },
  {
    violation_id: "V123458",
    operation_number: "1234567",
    operation_name: "Happy Kids Daycare",
    standard_number: "746.2501(a)",
    standard_description: "The caregiver must ensure the safety of all children in care.",
    violation_description: "During inspection, it was observed that cleaning supplies were stored within reach of children in the toddler classroom.",
    corrective_action: "Facility must ensure all cleaning supplies and potentially hazardous materials are stored out of children's reach.",
    risk_level: "Medium-High",
    corrected_at_inspection: "Yes",
    violation_date: "2023-12-15",
    corrected_date: "2023-12-15"
  },
  {
    violation_id: "V234567",
    operation_number: "2345678",
    operation_name: "Sunshine Learning Center",
    standard_number: "746.1305(a)",
    standard_description: "Background checks must be completed for all employees before they have contact with children.",
    violation_description: "During inspection, it was found that one new employee had contact with children before their background check was completed.",
    corrective_action: "Facility must ensure all employees complete background checks before having contact with children.",
    risk_level: "High",
    corrected_at_inspection: "Yes",
    violation_date: "2023-11-10",
    corrected_date: "2023-11-10"
  },
  {
    violation_id: "V345678",
    operation_number: "3456789",
    operation_name: "Little Explorers Academy",
    standard_number: "746.3101(a)",
    standard_description: "Staff must follow proper handwashing procedures.",
    violation_description: "During inspection, it was observed that 2 staff members did not properly wash hands after diapering procedures.",
    corrective_action: "Facility must ensure all staff follow proper handwashing procedures, especially after diapering.",
    risk_level: "Medium-High",
    corrected_at_inspection: "Yes",
    violation_date: "2024-01-28",
    corrected_date: "2024-01-28"
  },
  {
    violation_id: "V345679",
    operation_number: "3456789",
    operation_name: "Little Explorers Academy",
    standard_number: "746.3815(a)",
    standard_description: "Food must be stored at proper temperatures.",
    violation_description: "During inspection, it was observed that refrigerator temperature in kitchen was at 45°F, which is above the required maximum of 41°F.",
    corrective_action: "Facility must adjust refrigerator to maintain temperature at or below 41°F.",
    risk_level: "Medium",
    corrected_at_inspection: "No",
    violation_date: "2024-01-28",
    corrected_date: "2024-02-01"
  },
  {
    violation_id: "V345680",
    operation_number: "3456789",
    operation_name: "Little Explorers Academy",
    standard_number: "746.2415(a)",
    standard_description: "Daily schedules must be posted for each age group in care.",
    violation_description: "During inspection, it was observed that the daily schedule was not posted in the pre-kindergarten classroom.",
    corrective_action: "Facility must post daily schedules in all classrooms.",
    risk_level: "Low",
    corrected_at_inspection: "Yes",
    violation_date: "2024-01-28",
    corrected_date: "2024-01-28"
  },
  {
    violation_id: "V456789",
    operation_number: "4567890",
    operation_name: "Tiny Tots Child Care",
    standard_number: "746.2507(a)",
    standard_description: "Caregivers must supervise children at all times.",
    violation_description: "During inspection, it was observed that one child in the toddler classroom was not being adequately supervised for approximately 5 minutes.",
    corrective_action: "Facility must ensure adequate supervision of all children at all times.",
    risk_level: "High",
    corrected_at_inspection: "Yes",
    violation_date: "2023-12-05",
    corrected_date: "2023-12-05"
  },
  {
    violation_id: "V456790",
    operation_number: "4567890",
    operation_name: "Tiny Tots Child Care",
    standard_number: "746.3301(a)",
    standard_description: "Meals and snacks must meet nutritional guidelines.",
    violation_description: "During inspection, it was observed that snacks provided did not meet nutritional requirements for children's age groups.",
    corrective_action: "Facility must provide snacks that meet nutritional guidelines for all age groups.",
    risk_level: "Medium",
    corrected_at_inspection: "No",
    violation_date: "2023-12-05",
    corrected_date: "2023-12-12"
  },
  {
    violation_id: "V567890",
    operation_number: "5678901",
    operation_name: "Bright Beginnings Preschool",
    standard_number: "746.631(a)",
    standard_description: "Emergency evacuation plans must be posted in each classroom.",
    violation_description: "During inspection, it was observed that emergency evacuation plans were not posted in 2 classrooms.",
    corrective_action: "Facility must post emergency evacuation plans in all classrooms.",
    risk_level: "Medium",
    corrected_at_inspection: "Yes",
    violation_date: "2024-02-20",
    corrected_date: "2024-02-20"
  }
];

export const mockCities = [
  "Austin",
  "Dallas",
  "Fort Worth",
  "Houston",
  "San Antonio"
];

export const mockTotalItems = 95;